GET  http://127.0.0.1:8000/api/topico HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|VNw2a9QXxjzEamWELckyD9XVVViH9n9U5gyr7QCa

######################

POST   http://127.0.0.1:8000/api/topico HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|VNw2a9QXxjzEamWELckyD9XVVViH9n9U5gyr7QCa

{
    "topico":"oooi"
}

######################

PUT  http://127.0.0.1:8000/api/topico/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|VNw2a9QXxjzEamWELckyD9XVVViH9n9U5gyr7QCa

{
    "topico":"iihi"
}

######################

GET  http://127.0.0.1:8000/api/topico/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|VNw2a9QXxjzEamWELckyD9XVVViH9n9U5gyr7QCa

######################


DELETE  http://127.0.0.1:8000/api/topico/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|VNw2a9QXxjzEamWELckyD9XVVViH9n9U5gyr7QCa

######################


